language: java

jdk: oraclejdk8
branches:
  only:
  - master

script:
- ./gradlew check
- ./gradlew distZip

sudo: false

addons:
  apt:
    packages: oracle-java8-installer

before_install:
- rvm install 2.0.0
- gem install travis-custom-deploy

after_success:
- travis-custom-deploy stfp build/distributions/*.zip

